language: python
python: nightly
sudo: false
dist: trusty
matrix:
  fast_finish: true
jobs:
  include:
      - stage: build
        python: nightly
        script: ./build.sh
      - stage: test
        python: nightly
        script: ./install.sh
addons:
    apt:
      update: true

