language: python
python: nightly
sudo: false
dist: trusty
matrix:
  fast_finish: true
jobs:
  include:
      - stage: build
        python: nightly
        before_script: sudo apt-get update; sudo apt-get install coreutils realpath
        script: ./build.sh
      - stage: test
        python: nightly
        script: ./build.sh; ./install.sh
addons:
    apt:
      update: true

