language: python
python: nightly
sudo: false
dist: trusty
matrix:
  fast_finish: true
jobs:
  include:
      - stage: test
        python: nightly
        install: sudo apt-get update; sudo apt-get install coreutils realpath
        before_script: ./build.sh
        script: ./install.sh
addons:
    apt:
      update: true

